enum SdrModuleKind {
  source,
  decoder,
  utility,
  sink,
}

enum SdrModuleSupport {
  active,
  mapped,
  nativeSdk,
}

class SdrModuleDescriptor {
  const SdrModuleDescriptor({
    required this.id,
    required this.name,
    required this.kind,
    required this.upstreamPath,
    required this.support,
    required this.description,
    this.capabilities = const <String>[],
  });

  final String id;
  final String name;
  final SdrModuleKind kind;
  final String upstreamPath;
  final SdrModuleSupport support;
  final String description;
  final List<String> capabilities;
}

class SdrModuleCatalog {
  static const List<SdrModuleDescriptor> modules = <SdrModuleDescriptor>[
    // Sources shipped by upstream SDR++.
    SdrModuleDescriptor(
      id: 'rtl_tcp_source',
      name: 'RTL-TCP',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/rtl_tcp_source',
      support: SdrModuleSupport.active,
      description: 'Network RTL-SDR transport used by the Orange Pi receiver.',
      capabilities: <String>[
        'frequency',
        'sample rate',
        'gain',
        'PPM',
        'RTL AGC',
        'tuner AGC',
        'direct sampling',
        'offset tuning',
        'Bias-T',
      ],
    ),
    SdrModuleDescriptor(
      id: 'rtl_sdr_source',
      name: 'RTL-SDR USB',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/rtl_sdr_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Direct RTL-SDR USB source through librtlsdr.',
    ),
    SdrModuleDescriptor(
      id: 'file_source',
      name: 'File Source',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/file_source',
      support: SdrModuleSupport.active,
      description:
          'Native replay of SDR++ compatible IQ WAV files with in-file VFO tuning.',
      capabilities: <String>[
        '16-bit stereo IQ WAV',
        'Float32 IQ mode',
        'sample-rate detection',
        'center-frequency filename detection',
        'VFO offset tuning',
        'looped playback',
      ],
    ),
    SdrModuleDescriptor(
      id: 'audio_source',
      name: 'Audio Source',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/audio_source',
      support: SdrModuleSupport.mapped,
      description: 'Use an audio input device as a source.',
    ),
    SdrModuleDescriptor(
      id: 'network_source',
      name: 'Network Source',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/network_source',
      support: SdrModuleSupport.active,
      description:
          'Native SDR++ TCP/UDP raw IQ source with selectable sample format.',
      capabilities: <String>[
        'TCP client',
        'UDP',
        'Int8 IQ',
        'Int16 IQ',
        'Int32 IQ',
        'Float32 IQ',
        'configurable sample rate',
        'VFO offset tuning',
      ],
    ),
    SdrModuleDescriptor(
      id: 'sdrpp_server_source',
      name: 'SDR++ Server',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/sdrpp_server_source',
      support: SdrModuleSupport.active,
      description: 'Native SDR++ Server protocol source with remote tuning and server-driven sample rate.',
      capabilities: <String>[
        'remote tuning',
        'server-controlled sample rate',
        'Int16 IQ stream',
        'mobile native DSP integration',
      ],
    ),
    SdrModuleDescriptor(
      id: 'spyserver_source',
      name: 'SpyServer',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/spyserver_source',
      support: SdrModuleSupport.active,
      description: 'Native SpyServer source with IQ format negotiation, decimation and remote tuning.',
      capabilities: <String>[
        'remote tuning',
        'automatic decimation selection',
        'Uint8 / Int16 / Float32 IQ',
        'server gain control',
      ],
    ),
    SdrModuleDescriptor(
      id: 'spectran_http_source',
      name: 'Spectran HTTP',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/spectran_http_source',
      support: SdrModuleSupport.active,
      description: 'Official SDR++ Spectran HTTP IQ streaming runtime.',
      capabilities: <String>[
        'HTTP chunked IQ stream',
        'remote center-frequency control',
        'device-reported sample rate',
        'native mobile DSP integration',
      ],
    ),
    SdrModuleDescriptor(
      id: 'soapy_source',
      name: 'SoapySDR',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/soapy_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Generic SoapySDR hardware backend.',
    ),
    SdrModuleDescriptor(
      id: 'airspy_source',
      name: 'Airspy',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/airspy_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Airspy R2/Mini source.',
    ),
    SdrModuleDescriptor(
      id: 'airspyhf_source',
      name: 'Airspy HF+',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/airspyhf_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Airspy HF+ source.',
    ),
    SdrModuleDescriptor(
      id: 'bladerf_source',
      name: 'bladeRF',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/bladerf_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Nuand bladeRF source.',
    ),
    SdrModuleDescriptor(
      id: 'hackrf_source',
      name: 'HackRF',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/hackrf_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Great Scott Gadgets HackRF source.',
    ),
    SdrModuleDescriptor(
      id: 'limesdr_source',
      name: 'LimeSDR',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/limesdr_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Lime Microsystems SDR source.',
    ),
    SdrModuleDescriptor(
      id: 'plutosdr_source',
      name: 'PlutoSDR',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/plutosdr_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Analog Devices PlutoSDR source.',
    ),
    SdrModuleDescriptor(
      id: 'sdrplay_source',
      name: 'SDRplay',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/sdrplay_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'SDRplay RSP family source.',
    ),
    SdrModuleDescriptor(
      id: 'usrp_source',
      name: 'USRP',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/usrp_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Ettus USRP/UHD source.',
    ),
    SdrModuleDescriptor(
      id: 'perseus_source',
      name: 'Perseus',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/perseus_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Microtelecom Perseus source.',
    ),
    SdrModuleDescriptor(
      id: 'rfspace_source',
      name: 'RFspace',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/rfspace_source',
      support: SdrModuleSupport.active,
      description: 'Official SDR++ RFspace TCP control / UDP IQ runtime.',
      capabilities: <String>[
        'receiver sample-rate discovery',
        'remote tuning',
        'RF gain',
        '16-bit complex IQ',
        'native mobile DSP integration',
      ],
    ),
    SdrModuleDescriptor(
      id: 'hermes_source',
      name: 'Hermes',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/hermes_source',
      support: SdrModuleSupport.active,
      description: 'Official SDR++ Hermes/OpenHPSDR Metis runtime.',
      capabilities: <String>[
        '48/96/192/384 kSPS',
        'remote tuning',
        'LNA gain',
        'Metis UDP IQ',
        'native mobile DSP integration',
      ],
    ),
    SdrModuleDescriptor(
      id: 'hydrasdr_source',
      name: 'HydraSDR',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/hydrasdr_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'HydraSDR source.',
    ),
    SdrModuleDescriptor(
      id: 'rfnm_source',
      name: 'RFNM',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/rfnm_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'RFNM source.',
    ),
    SdrModuleDescriptor(
      id: 'sddc_source',
      name: 'SDDC',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/sddc_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'SDDC-compatible source.',
    ),
    SdrModuleDescriptor(
      id: 'fobossdr_source',
      name: 'FobosSDR',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/fobossdr_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'FobosSDR source.',
    ),
    SdrModuleDescriptor(
      id: 'harogic_source',
      name: 'Harogic',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/harogic_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Harogic spectrum receiver source.',
    ),
    SdrModuleDescriptor(
      id: 'spectran_source',
      name: 'Spectran V6',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/spectran_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'Aaronia Spectran V6 native source.',
    ),
    SdrModuleDescriptor(
      id: 'dragonlabs_source',
      name: 'DragonLabs',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/dragonlabs_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'DragonLabs SDR source.',
    ),
    SdrModuleDescriptor(
      id: 'kcsdr_source',
      name: 'KCSDR',
      kind: SdrModuleKind.source,
      upstreamPath: 'source_modules/kcsdr_source',
      support: SdrModuleSupport.nativeSdk,
      description: 'KCSDR source.',
    ),

    // Decoder modules.
    SdrModuleDescriptor(
      id: 'radio',
      name: 'Radio',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/radio',
      support: SdrModuleSupport.active,
      description: 'AM/NFM/WFM/SSB/DSB/CW receiver and radio post-processing.',
    ),
    SdrModuleDescriptor(
      id: 'dab_decoder',
      name: 'DAB Decoder',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/dab_decoder',
      support: SdrModuleSupport.mapped,
      description: 'Digital Audio Broadcasting decoder.',
    ),
    SdrModuleDescriptor(
      id: 'm17_decoder',
      name: 'M17 Decoder',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/m17_decoder',
      support: SdrModuleSupport.mapped,
      description: 'M17 digital voice decoder.',
    ),
    SdrModuleDescriptor(
      id: 'pager_decoder',
      name: 'Pager Decoder',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/pager_decoder',
      support: SdrModuleSupport.mapped,
      description: 'Pager protocol decoder.',
    ),
    SdrModuleDescriptor(
      id: 'vor_receiver',
      name: 'VOR Receiver',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/vor_receiver',
      support: SdrModuleSupport.mapped,
      description: 'VHF Omnidirectional Range receiver.',
    ),
    SdrModuleDescriptor(
      id: 'weather_sat_decoder',
      name: 'Weather Satellite',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/weather_sat_decoder',
      support: SdrModuleSupport.mapped,
      description: 'Weather satellite decoder.',
    ),
    SdrModuleDescriptor(
      id: 'meteor_demodulator',
      name: 'Meteor Demodulator',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/meteor_demodulator',
      support: SdrModuleSupport.mapped,
      description: 'Meteor satellite demodulator.',
    ),
    SdrModuleDescriptor(
      id: 'atv_decoder',
      name: 'ATV Decoder',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/atv_decoder',
      support: SdrModuleSupport.mapped,
      description: 'Analog television decoder.',
    ),
    SdrModuleDescriptor(
      id: 'kg_sstv_decoder',
      name: 'KG-SSTV Decoder',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/kg_sstv_decoder',
      support: SdrModuleSupport.mapped,
      description: 'KG-SSTV image decoder.',
    ),
    SdrModuleDescriptor(
      id: 'falcon9_decoder',
      name: 'Falcon 9 Decoder',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/falcon9_decoder',
      support: SdrModuleSupport.mapped,
      description: 'Falcon 9 telemetry decoder.',
    ),
    SdrModuleDescriptor(
      id: 'ryfi_decoder',
      name: 'RyFi Decoder',
      kind: SdrModuleKind.decoder,
      upstreamPath: 'decoder_modules/ryfi_decoder',
      support: SdrModuleSupport.mapped,
      description: 'RyFi decoder module.',
    ),

    // Utility / plugin-style modules.
    SdrModuleDescriptor(
      id: 'demo_module',
      name: 'Demo Module',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/demo_module',
      support: SdrModuleSupport.mapped,
      description: 'Upstream demonstration module used for module-host parity.',
    ),
    SdrModuleDescriptor(
      id: 'frequency_manager',
      name: 'Frequency Manager',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/frequency_manager',
      support: SdrModuleSupport.active,
      description: 'Presets and frequency bookmarks.',
    ),
    SdrModuleDescriptor(
      id: 'recorder',
      name: 'Recorder',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/recorder',
      support: SdrModuleSupport.active,
      description: 'Demodulated audio recording.',
    ),
    SdrModuleDescriptor(
      id: 'scanner',
      name: 'Scanner',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/scanner',
      support: SdrModuleSupport.active,
      description: 'Frequency scanning.',
    ),
    SdrModuleDescriptor(
      id: 'scheduler',
      name: 'Scheduler',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/scheduler',
      support: SdrModuleSupport.mapped,
      description: 'Scheduled receiver actions.',
    ),
    SdrModuleDescriptor(
      id: 'iq_exporter',
      name: 'IQ Exporter',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/iq_exporter',
      support: SdrModuleSupport.mapped,
      description: 'Export raw IQ samples.',
    ),
    SdrModuleDescriptor(
      id: 'rigctl_client',
      name: 'Rigctl Client',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/rigctl_client',
      support: SdrModuleSupport.mapped,
      description: 'Hamlib rig control client.',
    ),
    SdrModuleDescriptor(
      id: 'rigctl_server',
      name: 'Rigctl Server',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/rigctl_server',
      support: SdrModuleSupport.mapped,
      description: 'Hamlib-compatible rig control server.',
    ),
    SdrModuleDescriptor(
      id: 'discord_integration',
      name: 'Discord Integration',
      kind: SdrModuleKind.utility,
      upstreamPath: 'misc_modules/discord_integration',
      support: SdrModuleSupport.mapped,
      description: 'Discord rich presence integration.',
    ),

    // Sinks.
    SdrModuleDescriptor(
      id: 'android_audio_sink',
      name: 'Android Audio',
      kind: SdrModuleKind.sink,
      upstreamPath: 'sink_modules/android_audio_sink',
      support: SdrModuleSupport.active,
      description: 'Mobile audio playback sink.',
    ),
    SdrModuleDescriptor(
      id: 'audio_sink',
      name: 'Audio Sink',
      kind: SdrModuleKind.sink,
      upstreamPath: 'sink_modules/audio_sink',
      support: SdrModuleSupport.mapped,
      description: 'Desktop audio output sink.',
    ),
    SdrModuleDescriptor(
      id: 'network_sink',
      name: 'Network Sink',
      kind: SdrModuleKind.sink,
      upstreamPath: 'sink_modules/network_sink',
      support: SdrModuleSupport.mapped,
      description: 'Stream demodulated audio over the network.',
    ),
    SdrModuleDescriptor(
      id: 'new_portaudio_sink',
      name: 'New PortAudio',
      kind: SdrModuleKind.sink,
      upstreamPath: 'sink_modules/new_portaudio_sink',
      support: SdrModuleSupport.mapped,
      description: 'Current PortAudio desktop sink.',
    ),
    SdrModuleDescriptor(
      id: 'portaudio_sink',
      name: 'Legacy PortAudio',
      kind: SdrModuleKind.sink,
      upstreamPath: 'sink_modules/portaudio_sink',
      support: SdrModuleSupport.mapped,
      description: 'Legacy PortAudio sink kept for upstream parity.',
    ),
  ];

  static List<SdrModuleDescriptor> ofKind(SdrModuleKind kind) =>
      modules.where((module) => module.kind == kind).toList(growable: false);
}
